"""Initial schema

Revision ID: da10ec576e56
Revises: 
Create Date: 2026-06-23 16:57:06.675719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da10ec576e56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_frames', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('raw_frames', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('raw_frames', 'station_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('raw_frames', 'raw_frame',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_index(op.f('idx_raw_norad_ts'), table_name='raw_frames')
    op.drop_index(op.f('raw_frames_timestamp_idx'), table_name='raw_frames')
    op.alter_column('telemetry_frames', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('telemetry_frames', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('telemetry_frames', 'raw_frame_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('idx_telem_anomaly'), table_name='telemetry_frames', postgresql_where='(is_anomaly = true)')
    op.drop_index(op.f('idx_telem_norad_ts'), table_name='telemetry_frames')
    op.drop_index(op.f('telemetry_frames_timestamp_idx'), table_name='telemetry_frames')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('telemetry_frames_timestamp_idx'), 'telemetry_frames', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_telem_norad_ts'), 'telemetry_frames', ['norad_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_telem_anomaly'), 'telemetry_frames', ['norad_id', 'is_anomaly', sa.literal_column('timestamp DESC')], unique=False, postgresql_where='(is_anomaly = true)')
    op.alter_column('telemetry_frames', 'raw_frame_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('telemetry_frames', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('telemetry_frames', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('raw_frames_timestamp_idx'), 'raw_frames', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_raw_norad_ts'), 'raw_frames', ['norad_id', sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('raw_frames', 'raw_frame',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('raw_frames', 'station_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('raw_frames', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('raw_frames', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
